[[endpoints]]
# 备注: dmit-hk 
listen = "[::]:5000"
remote = "dmit-hk.19931115.xyz:6666"

[[endpoints]]
# 备注: rfc-hk 
listen = "[::]:5001"
remote = "rfc-hk.19931115.xyz:22"

[[endpoints]]
# 备注: rfc-jp 
listen = "[::]:5002"
remote = "rfc-jp.19931115.xyz:22"
